input_cube:
  path: EO_Data.zarr/s1sig0/EU
  variable_names: [VH, VV, absolute_orbit_number, relative_orbit_number, sensing_date]

output_cube:
  path: eo_cube_output.zarr
  format_name: zarr
  replace: true

cube_config:
  crs: EPSG:3035
  spatial_res: 20
  spatial_res_unit: meter
  chunk_size: [1, 512, 512]     # time, y, x

  variables:
    VH:
      dtype: int16
      fill_value: -9999
      valid_range: [-30000, 30000]
      scale_factor: 0.1
    VV:
      dtype: int16
      fill_value: -9999
      valid_range: [-30000, 30000]
      scale_factor: 0.1
    absolute_orbit_number:
      dtype: int32
      fill_value: -9999
    relative_orbit_number:
      dtype: int16
      fill_value: -9999
    sensing_date:
      dtype: int64
      fill_value: -9999
      units: seconds since 2014-10-01 00:00:00
      calendar: proleptic_gregorian
