apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: inca-processing-
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: "Allow"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 10

  workflowSpec:
    entrypoint: main
    securityContext:
      runAsUser: 74268
      fsGroup: 71473
    volumes:
      - name: eodc-mount
        persistentVolumeClaim:
          claimName: eodc-nfs-claim

    templates:
      - name: main
        steps:
          - - name: inca-parallel
              template: inca-pipeline
              arguments:
                parameters:
                  - name: var
                    value: "{{item}}"
              withParam: '["RR", "T2M", "GL", "RH2M", "P0", "UU", "VV", "TD2M"]'

      - name: inca-pipeline
        inputs:
          parameters:
            - name: var
            - name: ym
        steps:
          - - name: download-data
              template: download
              arguments:
                parameters:
                  - name: var
                    value: "{{inputs.parameters.var}}"
                  - name: ym
                    value: "{{inputs.parameters.ym}}"
          - - name: process-data
              template: process
              arguments:
                parameters:
                  - name: var
                    value: "{{inputs.parameters.var}}"
                  - name: ym
                    value: "{{inputs.parameters.ym}}"
                artifacts:
                  - name: inca-file
                    from: "{{steps.download-data.outputs.artifacts.inca-file}}"

      - name: download
        inputs:
          parameters:
            - name: var
            - name: ym
        container:
          image: ghcr.io/oscipal/image_zarr:latest
          imagePullPolicy: Always
          command: ["python"]
          args: ["inca_download.py", "{{inputs.parameters.var}}", "{{inputs.parameters.ym}}"]
        outputs:
          artifacts:
            - name: inca-file
              path: "/tmp/INCAL_HOURLY_{{inputs.parameters.var}}_202506.nc"
              archive:
                none: {}

      - name: process
        inputs:
          parameters:
            - name: var
            - name: ym
          artifacts:
            - name: inca-file
              path: "/tmp/INCAL_HOURLY_{{inputs.parameters.var}}_202506.nc"
        container:
          image: ghcr.io/oscipal/image_zarr:latest
          imagePullPolicy: Always
          command: ["python"]
          args: ["inca_write.py", "{{inputs.parameters.var}}", "{{inputs.parameters.ym}}"]
          volumeMounts:
            - name: eodc-mount
              mountPath: /eodc

      - name: compute-ym
        script:
          image: python:3.11
          command: ["python"]
          source: |
            import datetime
            from datetime import timedelta

            today = datetime.date.today()
            if today.day < 8:
                first_day_this_month = today.replace(day=1)
                last_month = first_day_this_month - timedelta(days=1)
                ym = last_month.strftime("%Y%m")
            else:
                ym = today.strftime("%Y%m")
              
            print(ym)
        outputs:
          parameters:
            - name: result
              valueFrom:
                path: /tmp/stdout
