[workspace]
authors = ["oscipal <otto.scipal@gmail.com>"]
channels = ["conda-forge"]
name = "zarr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
_libgcc_mutex = { version = "==0.1", build = "conda_forge" }
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
affine = { version = "==2.4.0", build = "pyhd8ed1ab_1" }
aiobotocore = { version = "==2.23.0", build = "pyhd8ed1ab_0" }
aiohappyeyeballs = { version = "==2.6.1", build = "pyhd8ed1ab_0" }
aiohttp = { version = "==3.12.7", build = "py311h2dc5d0c_0" }
aioitertools = { version = "==0.12.0", build = "pyhd8ed1ab_1" }
aiosignal = { version = "==1.3.2", build = "pyhd8ed1ab_0" }
aom = { version = "==3.9.1", build = "hac33072_0" }
asttokens = { version = "==2.4.1", build = "pyhd8ed1ab_0" }
attrs = { version = "==25.3.0", build = "pyh71513ae_0" }
aws-c-auth = { version = "==0.8.1", build = "h205f482_0" }
aws-c-cal = { version = "==0.8.1", build = "h1a47875_3" }
aws-c-common = { version = "==0.10.6", build = "hb9d3cd8_0" }
aws-c-compression = { version = "==0.3.0", build = "h4e1184b_5" }
aws-c-event-stream = { version = "==0.5.0", build = "h7959bf6_11" }
aws-c-http = { version = "==0.9.2", build = "hefd7a92_4" }
aws-c-io = { version = "==0.15.3", build = "hbf5b6a4_4" }
aws-c-mqtt = { version = "==0.11.0", build = "h11f4f37_12" }
aws-c-s3 = { version = "==0.7.9", build = "he1b24dc_1" }
aws-c-sdkutils = { version = "==0.2.2", build = "h4e1184b_0" }
aws-checksums = { version = "==0.2.2", build = "h4e1184b_4" }
aws-crt-cpp = { version = "==0.29.9", build = "he0e7f3f_2" }
aws-sdk-cpp = { version = "==1.11.489", build = "h4d475cb_0" }
azure-core-cpp = { version = "==1.14.0", build = "h5cfcd09_0" }
azure-identity-cpp = { version = "==1.10.0", build = "h113e628_0" }
azure-storage-blobs-cpp = { version = "==12.13.0", build = "h3cf044e_1" }
azure-storage-common-cpp = { version = "==12.8.0", build = "h736e048_1" }
azure-storage-files-datalake-cpp = { version = "==12.12.0", build = "ha633028_1" }
beautifulsoup4 = { version = "==4.13.4", build = "pyha770c72_0" }
blosc = { version = "==1.21.6", build = "he440d0b_1" }
bokeh = { version = "==3.7.3", build = "pyhd8ed1ab_0" }
boto3 = { version = "==1.38.27", build = "pyhd8ed1ab_0" }
botocore = { version = "==1.38.27", build = "pyge310_1234567_0" }
brotli = { version = "==1.1.0", build = "hd590300_1" }
brotli-bin = { version = "==1.1.0", build = "hd590300_1" }
brotli-python = { version = "==1.1.0", build = "py311hb755f60_1" }
brunsli = { version = "==0.1", build = "h9c3ff4c_0" }
bs4 = { version = "==4.13.4", build = "hd8ed1ab_0" }
bzip2 = { version = "==1.0.8", build = "h4bc722e_7" }
c-ares = { version = "==1.34.5", build = "hb9d3cd8_0" }
c-blosc2 = { version = "==2.15.2", build = "h3122c55_1" }
ca-certificates = { version = "==2024.7.4", build = "hbcca054_0" }
cairo = { version = "==1.18.0", build = "hebfffa5_3" }
capnproto = { version = "==1.0.2", build = "h766bdaa_3" }
certifi = { version = "==2025.4.26", build = "pyhd8ed1ab_0" }
cffi = { version = "==1.17.0", build = "py311ha8e6434_0" }
cfitsio = { version = "==4.6.2", build = "h44b4e7a_0" }
cftime = { version = "==1.6.4", build = "py311h9f3472d_1" }
charls = { version = "==2.4.2", build = "h59595ed_0" }
charset-normalizer = { version = "==3.4.2", build = "pyhd8ed1ab_0" }
click = { version = "==8.2.1", build = "pyh707e725_0" }
click-plugins = { version = "==1.1.1", build = "pyhd8ed1ab_1" }
cligj = { version = "==0.7.2", build = "pyhd8ed1ab_2" }
cloudpickle = { version = "==3.1.1", build = "pyhd8ed1ab_0" }
colorama = { version = "==0.4.6", build = "pyhd8ed1ab_1" }
comm = { version = "==0.2.2", build = "pyhd8ed1ab_0" }
contourpy = { version = "==1.2.1", build = "py311h9547e67_0" }
crc32c = { version = "==2.7.1", build = "py311h9ecbd09_1" }
cyrus-sasl = { version = "==2.1.27", build = "h54b06d7_7" }
cytoolz = { version = "==0.12.3", build = "py311h459d7ec_0" }
dask = { version = "==2025.5.1", build = "pyhd8ed1ab_0" }
dask-core = { version = "==2025.5.1", build = "pyhd8ed1ab_0" }
dask-gateway = { version = "==2025.4.0", build = "pyha7f0ed4_2" }
dav1d = { version = "==1.2.1", build = "hd590300_0" }
debugpy = { version = "==1.8.2", build = "py311h4332511_0" }
decorator = { version = "==5.1.1", build = "pyhd8ed1ab_0" }
deprecated = { version = "==1.2.18", build = "pyhd8ed1ab_0" }
distributed = { version = "==2025.5.1", build = "pyhd8ed1ab_0" }
donfig = { version = "==0.8.1.post1", build = "pyhd8ed1ab_1" }
exceptiongroup = { version = "==1.2.2", build = "pyhd8ed1ab_0" }
executing = { version = "==2.0.1", build = "pyhd8ed1ab_0" }
expat = { version = "==2.7.0", build = "h5888daf_0" }
fmt = { version = "==11.0.2", build = "h07f6e7f_1" }
font-ttf-dejavu-sans-mono = { version = "==2.37", build = "hab24e00_0" }
font-ttf-inconsolata = { version = "==3.0", build = "h77eed37_0" }
font-ttf-source-code-pro = { version = "==2.38", build = "h77eed37_0" }
font-ttf-ubuntu = { version = "==0.83", build = "h77eed37_3" }
fontconfig = { version = "==2.15.0", build = "h7e30c49_1" }
fonts-conda-ecosystem = { version = "==1", build = "0" }
fonts-conda-forge = { version = "==1", build = "0" }
freetype = { version = "==2.12.1", build = "h267a509_2" }
freexl = { version = "==2.0.0", build = "h743c826_0" }
frozenlist = { version = "==1.6.0", build = "py311h62d540b_0" }
fsspec = { version = "==2025.5.1", build = "pyhd8ed1ab_0" }
geos = { version = "==3.13.1", build = "h97f6797_0" }
geotiff = { version = "==1.7.4", build = "h239500f_2" }
gflags = { version = "==2.2.2", build = "he1b5a44_1004" }
giflib = { version = "==5.2.2", build = "hd590300_0" }
glog = { version = "==0.7.1", build = "hbabe93e_0" }
h2 = { version = "==4.2.0", build = "pyhd8ed1ab_0" }
hdf4 = { version = "==4.2.15", build = "h2a13503_7" }
hdf5 = { version = "==1.14.6", build = "nompi_h2d575fe_101" }
hpack = { version = "==4.1.0", build = "pyhd8ed1ab_0" }
hyperframe = { version = "==6.1.0", build = "pyhd8ed1ab_0" }
icu = { version = "==75.1", build = "he02047a_0" }
idna = { version = "==3.10", build = "pyhd8ed1ab_1" }
imagecodecs = { version = "==2024.12.30", build = "py311h9971d45_0" }
importlib-metadata = { version = "==8.2.0", build = "pyha770c72_0" }
importlib_metadata = { version = "==8.2.0", build = "hd8ed1ab_0" }
ipykernel = { version = "==6.29.5", build = "pyh3099207_0" }
ipython = { version = "==9.3.0", build = "pyhfa0c392_0" }
ipython_pygments_lexers = { version = "==1.1.1", build = "pyhd8ed1ab_0" }
jedi = { version = "==0.19.1", build = "pyhd8ed1ab_0" }
jinja2 = { version = "==3.1.6", build = "pyhd8ed1ab_0" }
jmespath = { version = "==1.0.1", build = "pyhd8ed1ab_1" }
json-c = { version = "==0.18", build = "h6688a6e_0" }
jupyter_client = { version = "==8.6.2", build = "pyhd8ed1ab_0" }
jupyter_core = { version = "==5.7.2", build = "py311h38be061_0" }
jxrlib = { version = "==1.1", build = "hd590300_3" }
kealib = { version = "==1.6.2", build = "h74a6b89_0" }
keyutils = { version = "==1.6.1", build = "h166bdaf_0" }
krb5 = { version = "==1.21.3", build = "h659f571_0" }
lcms2 = { version = "==2.16", build = "hb7c19ff_0" }
ld_impl_linux-64 = { version = "==2.40", build = "hf3520f5_7" }
lerc = { version = "==4.0.0", build = "h27087fc_0" }
libabseil = { version = "==20240722.0", build = "cxx17_hbbce691_4" }
libaec = { version = "==1.1.3", build = "h59595ed_0" }
libarchive = { version = "==3.7.7", build = "h75ea233_4" }
libarrow = { version = "==17.0.0", build = "h25a14c4_48_cpu" }
libarrow-acero = { version = "==17.0.0", build = "hcb10f89_48_cpu" }
libarrow-dataset = { version = "==17.0.0", build = "hcb10f89_48_cpu" }
libarrow-substrait = { version = "==17.0.0", build = "h08228c5_48_cpu" }
libavif16 = { version = "==1.3.0", build = "h766b0b6_0" }
libblas = { version = "==3.9.0", build = "28_h59b9bed_openblas" }
libbrotlicommon = { version = "==1.1.0", build = "hd590300_1" }
libbrotlidec = { version = "==1.1.0", build = "hd590300_1" }
libbrotlienc = { version = "==1.1.0", build = "hd590300_1" }
libcblas = { version = "==3.9.0", build = "28_he106b2a_openblas" }
libcrc32c = { version = "==1.1.2", build = "h9c3ff4c_0" }
libcurl = { version = "==8.14.1", build = "h332b0f4_0" }
libdeflate = { version = "==1.23", build = "h86f0d12_0" }
libedit = { version = "==3.1.20191231", build = "he28a2e2_2" }
libev = { version = "==4.33", build = "hd590300_2" }
libevent = { version = "==2.1.12", build = "hf998b51_1" }
libexpat = { version = "==2.7.0", build = "h5888daf_0" }
libffi = { version = "==3.4.2", build = "h7f98852_5" }
libgcc = { version = "==15.1.0", build = "h767d61c_2" }
libgcc-ng = { version = "==15.1.0", build = "h69a702a_2" }
libgdal = { version = "==3.10.3", build = "h3b705f5_11" }
libgdal-core = { version = "==3.10.3", build = "hab2de9c_5" }
libgdal-fits = { version = "==3.10.3", build = "hd249192_5" }
libgdal-grib = { version = "==3.10.3", build = "h928e5b2_5" }
libgdal-hdf4 = { version = "==3.10.3", build = "h9f77858_5" }
libgdal-hdf5 = { version = "==3.10.3", build = "heb3e146_5" }
libgdal-jp2openjpeg = { version = "==3.10.3", build = "h021fd61_5" }
libgdal-kea = { version = "==3.10.3", build = "hb47621c_5" }
libgdal-netcdf = { version = "==3.10.3", build = "hda9de04_5" }
libgdal-pdf = { version = "==3.10.3", build = "h7544357_5" }
libgdal-pg = { version = "==3.10.3", build = "h371d8d8_5" }
libgdal-postgisraster = { version = "==3.10.3", build = "h371d8d8_5" }
libgdal-tiledb = { version = "==3.10.3", build = "h7fe9b51_5" }
libgdal-xls = { version = "==3.10.3", build = "hbf74d7f_5" }
libgfortran = { version = "==3.0.0", build = "1" }
libgfortran-ng = { version = "==14.1.0", build = "h69a702a_0" }
libgfortran5 = { version = "==14.1.0", build = "hc5f4f2c_0" }
libglib = { version = "==2.82.2", build = "h2ff4ddf_1" }
libgomp = { version = "==15.1.0", build = "h767d61c_2" }
libgoogle-cloud = { version = "==2.35.0", build = "h2b5623c_0" }
libgoogle-cloud-storage = { version = "==2.35.0", build = "h0121fbd_0" }
libgrpc = { version = "==1.67.1", build = "h25350d4_2" }
libhwy = { version = "==1.2.0", build = "hf40a0c7_0" }
libiconv = { version = "==1.18", build = "h4ce23a2_1" }
libjpeg-turbo = { version = "==3.1.0", build = "hb9d3cd8_0" }
libjxl = { version = "==0.11.1", build = "h7b0646d_1" }
libkml = { version = "==1.3.0", build = "hf539b9f_1021" }
liblapack = { version = "==3.9.0", build = "28_h7ac8fdf_openblas" }
liblzma = { version = "==5.8.1", build = "hb9d3cd8_1" }
liblzma-devel = { version = "==5.8.1", build = "hb9d3cd8_1" }
libnetcdf = { version = "==4.9.2", build = "nompi_h0134ee8_117" }
libnghttp2 = { version = "==1.64.0", build = "h161d5f1_0" }
libnsl = { version = "==2.0.1", build = "hd590300_0" }
libntlm = { version = "==1.8", build = "hb9d3cd8_0" }
libopenblas = { version = "==0.3.28", build = "pthreads_h94d23a6_0" }
libparquet = { version = "==17.0.0", build = "h081d1f1_48_cpu" }
libpng = { version = "==1.6.47", build = "h943b412_0" }
libpq = { version = "==17.5", build = "h27ae623_0" }
libprotobuf = { version = "==5.28.3", build = "h6128344_1" }
libre2-11 = { version = "==2024.7.2", build = "hbbce691_2" }
librttopo = { version = "==1.1.0", build = "hd718a1a_18" }
libsodium = { version = "==1.0.18", build = "h36c2ea0_1" }
libspatialite = { version = "==5.1.0", build = "he17ca71_14" }
libsqlite = { version = "==3.50.1", build = "hee588c1_0" }
libssh2 = { version = "==1.11.1", build = "hcf80075_0" }
libstdcxx = { version = "==15.1.0", build = "h8f9b012_2" }
libstdcxx-ng = { version = "==15.1.0", build = "h4852527_2" }
libthrift = { version = "==0.21.0", build = "h0e7cc3e_0" }
libtiff = { version = "==4.7.0", build = "hd9ff511_4" }
libutf8proc = { version = "==2.10.0", build = "h202a827_0" }
libuuid = { version = "==2.38.1", build = "h0b41bf4_0" }
libwebp-base = { version = "==1.5.0", build = "h851e524_0" }
libxcb = { version = "==1.16", build = "hb9d3cd8_1" }
libxml2 = { version = "==2.13.8", build = "h4bc477f_0" }
libxslt = { version = "==1.1.39", build = "h76b75d6_0" }
libzip = { version = "==1.11.2", build = "h6991a6a_0" }
libzlib = { version = "==1.3.1", build = "h4ab18f5_1" }
libzopfli = { version = "==1.0.3", build = "h9c3ff4c_0" }
locket = { version = "==1.0.0", build = "pyhd8ed1ab_0" }
lz4 = { version = "==4.4.4", build = "py311h8c6ae76_0" }
lz4-c = { version = "==1.10.0", build = "h5888daf_1" }
lzo = { version = "==2.10", build = "hd590300_1001" }
markupsafe = { version = "==2.1.5", build = "py311h459d7ec_0" }
matplotlib-inline = { version = "==0.1.7", build = "pyhd8ed1ab_0" }
minizip = { version = "==4.0.7", build = "h05a5f5f_3" }
msgpack-python = { version = "==1.0.8", build = "py311h52f7536_0" }
multidict = { version = "==6.4.4", build = "py311h2dc5d0c_0" }
narwhals = { version = "==1.41.0", build = "pyhe01879c_0" }
ncurses = { version = "==6.5", build = "h59595ed_0" }
nest-asyncio = { version = "==1.6.0", build = "pyhd8ed1ab_0" }
netcdf4 = { version = "==1.7.2", build = "nompi_py311h8b974bf_102" }
nspr = { version = "==4.36", build = "h5888daf_0" }
nss = { version = "==3.112", build = "h159eef7_0" }
numcodecs = { version = "==0.16.1", build = "py311h7db5c69_0" }
numpy = { version = "==2.1.0", build = "py311hed25524_0" }
openjpeg = { version = "==2.5.3", build = "h5fbd93e_0" }
openldap = { version = "==2.6.10", build = "he970967_0" }
openssl = { version = "==3.5.0", build = "h7b32b05_1" }
orc = { version = "==2.0.3", build = "h12ee42a_2" }
packaging = { version = "==24.1", build = "pyhd8ed1ab_0" }
pandas = { version = "==2.2.2", build = "py311h14de704_1" }
parso = { version = "==0.8.4", build = "pyhd8ed1ab_0" }
partd = { version = "==1.4.2", build = "pyhd8ed1ab_0" }
pcre2 = { version = "==10.44", build = "hc749103_2" }
pexpect = { version = "==4.9.0", build = "pyhd8ed1ab_0" }
pickleshare = { version = "==0.7.5", build = "py_1003" }
pillow = { version = "==10.4.0", build = "py311h82a398c_0" }
pip = { version = "==24.2", build = "pyhd8ed1ab_0" }
pixman = { version = "==0.46.0", build = "h29eaf8c_0" }
platformdirs = { version = "==4.2.2", build = "pyhd8ed1ab_0" }
poppler = { version = "==24.12.0", build = "hd7b24de_2" }
poppler-data = { version = "==0.4.12", build = "hd8ed1ab_0" }
postgresql = { version = "==17.5", build = "h607a889_0" }
proj = { version = "==9.6.2", build = "h0054346_0" }
prompt-toolkit = { version = "==3.0.47", build = "pyha770c72_0" }
propcache = { version = "==0.3.1", build = "py311h2dc5d0c_0" }
psutil = { version = "==6.0.0", build = "py311h331c9d8_0" }
pthread-stubs = { version = "==0.4", build = "h36c2ea0_1001" }
ptyprocess = { version = "==0.7.0", build = "pyhd3deb0d_0" }
pure_eval = { version = "==0.2.3", build = "pyhd8ed1ab_0" }
pyarrow = { version = "==17.0.0", build = "py311hbd00459_1" }
pyarrow-core = { version = "==17.0.0", build = "py311h4510849_1_cpu" }
pycparser = { version = "==2.22", build = "pyh29332c3_1" }
pygments = { version = "==2.18.0", build = "pyhd8ed1ab_0" }
pyparsing = { version = "==3.2.3", build = "pyhd8ed1ab_1" }
pyproj = { version = "==3.7.1", build = "py311h0960b38_1" }
pysocks = { version = "==1.7.1", build = "pyha55dd90_7" }
pystac = { version = "==1.13.0", build = "pyhd8ed1ab_0" }
pystac-client = { version = "==0.8.6", build = "pyhd8ed1ab_0" }
python = { version = "==3.11.4", build = "hab00c5b_0_cpython" }
python-dateutil = { version = "==2.9.0", build = "pyhd8ed1ab_0" }
python-dotenv = { version = "==1.1.1", build = "pyhe01879c_0" }
python-tzdata = { version = "==2025.2", build = "pyhd8ed1ab_0" }
python_abi = { version = "==3.11", build = "4_cp311" }
pytz = { version = "==2025.2", build = "pyhd8ed1ab_0" }
pyyaml = { version = "==6.0.2", build = "py311h61187de_0" }
pyzmq = { version = "==26.0.3", build = "py311h08a0b41_0" }
rasterio = { version = "==1.4.3", build = "py311he01b476_1" }
rav1e = { version = "==0.7.1", build = "h8fae777_3" }
re2 = { version = "==2024.7.2", build = "h9925aae_2" }
readline = { version = "==8.2", build = "h8228510_1" }
requests = { version = "==2.32.3", build = "pyhd8ed1ab_1" }
rioxarray = { version = "==0.19.0", build = "pyhd8ed1ab_0" }
s2n = { version = "==1.5.9", build = "h0fd0ee4_0" }
s3fs = { version = "==2025.5.1", build = "pyhd8ed1ab_0" }
s3transfer = { version = "==0.13.0", build = "pyhd8ed1ab_0" }
scipy = { version = "==1.15.2", build = "py311h8f841c2_0" }
setuptools = { version = "==71.0.4", build = "pyhd8ed1ab_0" }
six = { version = "==1.16.0", build = "pyh6c4a22f_0" }
snappy = { version = "==1.2.1", build = "ha2e4443_0" }
snuggs = { version = "==1.4.7", build = "pyhd8ed1ab_2" }
sortedcontainers = { version = "==2.4.0", build = "pyhd8ed1ab_1" }
soupsieve = { version = "==2.7", build = "pyhd8ed1ab_0" }
spdlog = { version = "==1.15.1", build = "hb29a8c4_0" }
sqlite = { version = "==3.50.1", build = "h9eae976_0" }
stack_data = { version = "==0.6.2", build = "pyhd8ed1ab_0" }
stackstac = { version = "==0.5.1", build = "pyhd8ed1ab_1" }
svt-av1 = { version = "==3.0.2", build = "h5888daf_0" }
tblib = { version = "==3.1.0", build = "pyhd8ed1ab_0" }
tifffile = { version = "==2024.12.12", build = "pyhd8ed1ab_0" }
tiledb = { version = "==2.27.2", build = "he4dccf3_0" }
tk = { version = "==8.6.13", build = "noxft_h4845f30_101" }
toolz = { version = "==1.0.0", build = "pyhd8ed1ab_1" }
tornado = { version = "==6.4.1", build = "py311h331c9d8_0" }
tqdm = { version = "==4.67.1", build = "pyhd8ed1ab_1" }
traitlets = { version = "==5.14.3", build = "pyhd8ed1ab_1" }
typing-extensions = { version = "==4.12.2", build = "hd8ed1ab_0" }
typing_extensions = { version = "==4.12.2", build = "pyha770c72_0" }
tzcode = { version = "==2025b", build = "hb9d3cd8_0" }
tzdata = { version = "==2025b", build = "h78e105d_0" }
uriparser = { version = "==0.9.8", build = "hac33072_0" }
urllib3 = { version = "==2.4.0", build = "pyhd8ed1ab_0" }
wcwidth = { version = "==0.2.13", build = "pyhd8ed1ab_0" }
wheel = { version = "==0.43.0", build = "pyhd8ed1ab_1" }
wrapt = { version = "==1.17.2", build = "py311h9ecbd09_0" }
xarray = { version = "==2025.4.0", build = "pyhd8ed1ab_0" }
xerces-c = { version = "==3.2.5", build = "h988505b_2" }
xorg-kbproto = { version = "==1.0.7", build = "hb9d3cd8_1003" }
xorg-libice = { version = "==1.1.2", build = "hb9d3cd8_0" }
xorg-libsm = { version = "==1.2.6", build = "he73a12e_0" }
xorg-libx11 = { version = "==1.8.9", build = "hb711507_1" }
xorg-libxau = { version = "==1.0.11", build = "hd590300_0" }
xorg-libxdmcp = { version = "==1.1.3", build = "h7f98852_0" }
xorg-libxext = { version = "==1.3.4", build = "h0b41bf4_2" }
xorg-libxrender = { version = "==0.9.11", build = "hd590300_0" }
xorg-renderproto = { version = "==0.11.1", build = "hb9d3cd8_1003" }
xorg-xextproto = { version = "==7.3.0", build = "hb9d3cd8_1004" }
xorg-xproto = { version = "==7.0.31", build = "hb9d3cd8_1008" }
xyzservices = { version = "==2025.4.0", build = "pyhd8ed1ab_0" }
xz = { version = "==5.8.1", build = "hbcc6ac9_1" }
xz-gpl-tools = { version = "==5.8.1", build = "hbcc6ac9_1" }
xz-tools = { version = "==5.8.1", build = "hb9d3cd8_1" }
yaml = { version = "==0.2.5", build = "h7f98852_2" }
yarl = { version = "==1.20.0", build = "py311h2dc5d0c_0" }
zarr = { version = "==3.0.8", build = "pyhd8ed1ab_0" }
zeromq = { version = "==4.3.5", build = "h75354e8_4" }
zfp = { version = "==1.0.1", build = "h5888daf_2" }
zict = { version = "==3.0.0", build = "pyhd8ed1ab_1" }
zipp = { version = "==3.19.2", build = "pyhd8ed1ab_0" }
zlib = { version = "==1.3.1", build = "h4ab18f5_1" }
zlib-ng = { version = "==2.2.4", build = "h7955e40_0" }
zstandard = { version = "==0.23.0", build = "py311h9ecbd09_2" }
zstd = { version = "==1.5.7", build = "hb8e6e7a_2" }

[pypi-dependencies]
eodc = "==2025.6.1"
